"""
🚀 NUCLEAR AGENT MIGRATION HELPER
Universal helper for migrating all agents to the single-table architecture.
Provides common save patterns for all agent types.
"""
from typing import Dict, Any, Optional
import logging
from apps.api.services.universal_output_service import get_universal_output_service

logger = logging.getLogger(__name__)


class NuclearAgentMigration:
    """Helper class for migrating agents to universal output architecture."""

    @staticmethod
    async def save_agent_output(
        agent_type: str,
        output_data: Dict[str, Any],
        org_id: str,
        user_id: str,
        session_id: Optional[str] = None,
        campaign_id: Optional[str] = None,
        client_id: Optional[str] = None  # NEW: Required for agency organizations
    ) -> Dict[str, Any]:
        """
        Universal save function for any agent type.
        Replaces all agent-specific save patterns with single unified approach.

        Args:
            agent_type: Type of agent (persona, analytics, roi_budget, etc.)
            output_data: Complete output data from agent
            org_id: Organization ID
            user_id: User ID
            session_id: Optional session ID
            campaign_id: Optional campaign ID
            client_id: Required for AGENCY orgs, NULL for SME orgs

        Returns:
            Saved output record
        """
        service = get_universal_output_service()

        # Extract common fields
        title = output_data.get('title', f'{agent_type.title()} Analysis')
        summary = output_data.get('summary', f'Generated by {agent_type} agent')
        output_type = output_data.get('output_type', 'analysis')

        # Prepare complete content - ZERO data loss
        # Note: We do NOT delete 'title' or 'summary' from content because:
        # - Record-level 'title' is for database identification (e.g., "Marcus Jensen - VP of Operations")
        # - Content-level 'title' is structured data (e.g., job title "VP of Operations")
        # - These serve different purposes and are not duplicates
        complete_content = output_data.get('content', output_data)

        # Get confidence score based on agent type
        confidence_scores = {
            'persona': 0.85,
            'analytics': 0.9,
            'roi_budget': 0.88,
            'quick_wins': 0.92,
            'competitive_intelligence': 0.85,
            'client_success': 0.87,
            'ad_creative': 0.9,
            'campaign_planning': 0.88
        }
        confidence_score = confidence_scores.get(agent_type, 0.85)

        try:
            result = await service.save_agent_output(
                agent_type=agent_type,
                output_type=output_type,
                content=complete_content,  # Complete data preserved
                title=title,
                summary=summary,
                org_id=org_id,
                user_id=user_id,
                session_id=session_id,
                campaign_id=campaign_id,
                client_id=client_id,  # Pass client_id for schema routing
                metadata={
                    'agent_type': agent_type,
                    'nuclear_migration': True,
                    'original_structure_preserved': True
                },
                confidence_score=confidence_score
            )

            logger.info(
                f"✅ {agent_type.upper()} output saved via nuclear: {result['id']} "
                f"(client_id: {client_id or 'N/A'})"
            )
            return result

        except Exception as e:
            logger.error(f"Failed to save {agent_type} output: {e}")
            raise


# Agent-specific convenience functions
async def save_persona_output(
    persona_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None,
    client_id: Optional[str] = None  # NEW: Required for agency organizations
) -> Dict[str, Any]:
    """
    Save persona agent output.

    Args:
        persona_data: Complete persona data
        org_id: Organization ID
        user_id: User ID
        session_id: Optional session ID
        campaign_id: Optional campaign ID
        client_id: Required for AGENCY orgs, NULL for SME orgs
    """
    return await NuclearAgentMigration.save_agent_output(
        agent_type="persona",
        output_data=persona_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id,
        client_id=client_id  # Pass client_id for schema routing
    )


async def save_analytics_output(
    analytics_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save analytics agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="analytics",
        output_data=analytics_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_roi_budget_output(
    roi_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save ROI & Budget agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="roi_budget",
        output_data=roi_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_quick_wins_output(
    quick_wins_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save Quick Wins agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="quick_wins",
        output_data=quick_wins_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_competitive_intelligence_output(
    competitive_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save Competitive Intelligence agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="competitive_intelligence",
        output_data=competitive_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_client_success_output(
    client_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save Client Success agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="client_success",
        output_data=client_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_ad_creative_output(
    creative_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save Ad Creative agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="ad_creative",
        output_data=creative_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


async def save_campaign_planning_output(
    campaign_data: Dict[str, Any],
    org_id: str,
    user_id: str,
    session_id: Optional[str] = None,
    campaign_id: Optional[str] = None
) -> Dict[str, Any]:
    """Save Campaign Execution agent output."""
    return await NuclearAgentMigration.save_agent_output(
        agent_type="campaign_planning",
        output_data=campaign_data,
        org_id=org_id,
        user_id=user_id,
        session_id=session_id,
        campaign_id=campaign_id
    )


# Export for easy import
__all__ = [
    'NuclearAgentMigration',
    'save_persona_output',
    'save_analytics_output',
    'save_roi_budget_output',
    'save_quick_wins_output',
    'save_competitive_intelligence_output',
    'save_client_success_output',
    'save_ad_creative_output',
    'save_campaign_planning_output'
]