-- ============================================================================
-- create_extensions_schemas_enums
-- Extensions, schemas and enum types. Applied first; everything else depends on it.
-- ============================================================================

-- Schema provenance
-- -----------------
-- These layered migrations were split, unchanged, from one dump that was
-- generated by applying the original migration chain to a clean database.
-- Three classes of object pg_dump does not emit are included explicitly:
-- extensions (CREATE EXTENSION), RBAC reference data (roles, permissions and
-- role_permissions, in seed_rbac_reference_data) and pg_cron jobs (in
-- schedule_cron_jobs). Multitenancy: SME data lives in "public", agency data in
-- "agency"; Row Level Security is the tenant-isolation boundary.

-- ---------------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- ---------------------------------------------------------------------------
-- 2. Schema: tables, functions, views, indexes, triggers and RLS policies
-- ---------------------------------------------------------------------------



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "agency";


ALTER SCHEMA "agency" OWNER TO "postgres";


COMMENT ON SCHEMA "agency" IS 'Separate schema for agency users managing multiple clients. SME users remain in public schema for zero risk to existing functionality.';



CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'get_top_performing_outputs dropped - requires rewrite to cast double precision to numeric. Migration 172.';



CREATE TYPE "public"."business_model_enum" AS ENUM (
    'B2B',
    'B2C',
    'B2B2C',
    'Subscription',
    'Marketplace',
    'Freemium',
    'Transaction-based',
    'Advertising',
    'Hybrid'
);


ALTER TYPE "public"."business_model_enum" OWNER TO "postgres";


CREATE TYPE "public"."company_size_enum" AS ENUM (
    '1-10 employees',
    '11-50 employees',
    '51-200 employees',
    '201-500 employees',
    '501-1000 employees',
    '1000+ employees'
);


ALTER TYPE "public"."company_size_enum" OWNER TO "postgres";


COMMENT ON TYPE "public"."company_size_enum" IS 'User-friendly company size ranges aligned with frontend';



CREATE TYPE "public"."company_stage_enum" AS ENUM (
    'Idea',
    'MVP',
    'Early Traction',
    'Growth',
    'Scale',
    'Mature'
);


ALTER TYPE "public"."company_stage_enum" OWNER TO "postgres";


CREATE TYPE "public"."funding_status_enum" AS ENUM (
    'Bootstrapped',
    'Pre-seed',
    'Seed',
    'Series A',
    'Series B',
    'Series C+',
    'Public',
    'Acquired'
);


ALTER TYPE "public"."funding_status_enum" OWNER TO "postgres";


CREATE TYPE "public"."industry_enum" AS ENUM (
    'SaaS/Software',
    'E-commerce',
    'Professional Services',
    'Manufacturing',
    'Healthcare',
    'Retail',
    'Financial Services',
    'Education',
    'Non-profit',
    'Media & Entertainment',
    'Real Estate',
    'Transportation',
    'Energy',
    'Agriculture',
    'Other',
    'Advertising & Marketing',
    'Agriculture & Farming',
    'Automotive',
    'Construction',
    'Consulting',
    'Energy & Utilities',
    'Entertainment & Media',
    'Finance & Banking',
    'Food & Beverage',
    'Hospitality & Tourism',
    'Insurance',
    'Legal Services',
    'Technology',
    'Telecommunications',
    'Transportation & Logistics'
);


ALTER TYPE "public"."industry_enum" OWNER TO "postgres";


COMMENT ON TYPE "public"."industry_enum" IS 'User-friendly industry categories aligned with frontend';

SET default_tablespace = '';

SET default_table_access_method = "heap";








-- ---------------------------------------------------------------------------
-- 3. RBAC reference data
--    Created by the original migration chain, NOT by seed.sql. Without this
--    the application's authorization model is empty.
-- ---------------------------------------------------------------------------
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--

-- The original chain inserted this data before these triggers existed.
-- A consolidated baseline creates the schema first, so the triggers would
-- fire on load. Disable them for this trusted reference data only.
SET session_replication_role = replica;


--
-- PostgreSQL database dump complete
--




SET session_replication_role = origin;

-- ---------------------------------------------------------------------------
-- 6. Restore search_path
--    pg_dump sets search_path to empty for its own session
--    (set_config('search_path', '', false) — session-scoped, not local).
--    Supabase applies migrations and seed data over the same session, so
--    leaving it empty breaks seed.sql's unqualified statements, e.g.
--    "REFRESH MATERIALIZED VIEW org_metrics_cache".
-- ---------------------------------------------------------------------------
SET search_path TO "public", "agency", "extensions";